### ISSUE TITLE
inspired by 써주세욤

### ISSUE THREAD

**Issue by MaxKim-J** [weehan-dev-2020/HYClock#1]
리드미에 써주세여!!! ㅎㅎㅎㅎㅎㅎㅎㅎ
https://github.com/MaxKim-J/HUFS-Semester-Clock-Extension 
이상한 이슈 남겨서 ㅈㅅ합니다;; 오늘도 신나는 개발~~

**Comment by Neulhan** [comment]
ㅋㅋ 아직 프로젝트 제대로 시작 안해서 신경 못썼네요 고쳐놓겠슘당
